#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =  -IcJSON/include
CFLAGS =  -Wall -std=c++0x -fexceptions -DDLL_BUILD
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG_WIN =  $(INC) -Iinclude
CFLAGS_DEBUG_WIN =  $(CFLAGS) -std=c++0x -g -finput-charset=iso-8859-1 -pthread
RESINC_DEBUG_WIN =  $(RESINC)
RCFLAGS_DEBUG_WIN =  $(RCFLAGS)
LIBDIR_DEBUG_WIN =  $(LIBDIR)
LIB_DEBUG_WIN = $(LIB) -lcurl-4
LDFLAGS_DEBUG_WIN =  $(LDFLAGS)
OBJDIR_DEBUG_WIN = obj/Debug
DEP_DEBUG_WIN = 
OUT_DEBUG_WIN = bin/Debug/wcwebcamclient.so

INC_RELEASE_WIN =  $(INC) -Iinclude
CFLAGS_RELEASE_WIN =  $(CFLAGS) -O2 -std=c++0x -pthread
RESINC_RELEASE_WIN =  $(RESINC)
RCFLAGS_RELEASE_WIN =  $(RCFLAGS)
LIBDIR_RELEASE_WIN =  $(LIBDIR)
LIB_RELEASE_WIN = $(LIB) -lcurl-4
LDFLAGS_RELEASE_WIN =  $(LDFLAGS) -s
OBJDIR_RELEASE_WIN = obj/Release
DEP_RELEASE_WIN = 
OUT_RELEASE_WIN = bin/Release/wcwebcamclient.so

INC_DEBUG_LINUX =  $(INC) -Iinclude
CFLAGS_DEBUG_LINUX =  $(CFLAGS) -std=c++0x -fPIC -g -finput-charset=iso-8859-1 -pthread
RESINC_DEBUG_LINUX =  $(RESINC)
RCFLAGS_DEBUG_LINUX =  $(RCFLAGS)
LIBDIR_DEBUG_LINUX =  $(LIBDIR)
LIB_DEBUG_LINUX = $(LIB) -lcurl
LDFLAGS_DEBUG_LINUX =  $(LDFLAGS)
OBJDIR_DEBUG_LINUX = obj/Debug
DEP_DEBUG_LINUX = 
OUT_DEBUG_LINUX = bin/Debug/wcwebcamclient.so

INC_RELEASE_LINUX =  $(INC) -Iinclude
CFLAGS_RELEASE_LINUX =  $(CFLAGS) -O2 -std=c++0x -fPIC -pthread
RESINC_RELEASE_LINUX =  $(RESINC)
RCFLAGS_RELEASE_LINUX =  $(RCFLAGS)
LIBDIR_RELEASE_LINUX =  $(LIBDIR)
LIB_RELEASE_LINUX = $(LIB) -lcurl
LDFLAGS_RELEASE_LINUX =  $(LDFLAGS) -s
OBJDIR_RELEASE_LINUX = obj/Release
DEP_RELEASE_LINUX = 
OUT_RELEASE_LINUX = bin/Release/wcwebcamclient.so

OBJ_DEBUG_WIN = $(OBJDIR_DEBUG_WIN)/src/wcHTTP2AsyncBackground.o $(OBJDIR_DEBUG_WIN)/src/NotifyObj.o $(OBJDIR_DEBUG_WIN)/src/tsCURLM.o $(OBJDIR_DEBUG_WIN)/src/tsInteger.o $(OBJDIR_DEBUG_WIN)/src/tsObject.o $(OBJDIR_DEBUG_WIN)/src/tsSeq.o $(OBJDIR_DEBUG_WIN)/src/tsStringList.o $(OBJDIR_DEBUG_WIN)/src/wcCURLClient.o $(OBJDIR_DEBUG_WIN)/src/wcCallbacks.o $(OBJDIR_DEBUG_WIN)/src/wcConsts.o $(OBJDIR_DEBUG_WIN)/src/wcHTTP2BackgroundTask.o $(OBJDIR_DEBUG_WIN)/src/wcHTTP2SettingsIntf.o $(OBJDIR_DEBUG_WIN)/src/wcJSON.o $(OBJDIR_DEBUG_WIN)/src/wcMemoryStream.o $(OBJDIR_DEBUG_WIN)/src/wcStreaming.o $(OBJDIR_DEBUG_WIN)/src/wcThread.o $(OBJDIR_DEBUG_WIN)/src/wcUtils.o $(OBJDIR_DEBUG_WIN)/wcwebcamclient.o $(OBJDIR_DEBUG_WIN)/cJSON/src/cJSON.o $(OBJDIR_DEBUG_WIN)/cJSON/src/cJSON_Utils.o

OBJ_RELEASE_WIN = $(OBJDIR_RELEASE_WIN)/src/wcHTTP2AsyncBackground.o $(OBJDIR_RELEASE_WIN)/src/NotifyObj.o $(OBJDIR_RELEASE_WIN)/src/tsCURLM.o $(OBJDIR_RELEASE_WIN)/src/tsInteger.o $(OBJDIR_RELEASE_WIN)/src/tsObject.o $(OBJDIR_RELEASE_WIN)/src/tsSeq.o $(OBJDIR_RELEASE_WIN)/src/tsStringList.o $(OBJDIR_RELEASE_WIN)/src/wcCURLClient.o $(OBJDIR_RELEASE_WIN)/src/wcCallbacks.o $(OBJDIR_RELEASE_WIN)/src/wcConsts.o $(OBJDIR_RELEASE_WIN)/src/wcHTTP2BackgroundTask.o $(OBJDIR_RELEASE_WIN)/src/wcHTTP2SettingsIntf.o $(OBJDIR_RELEASE_WIN)/src/wcJSON.o $(OBJDIR_RELEASE_WIN)/src/wcMemoryStream.o $(OBJDIR_RELEASE_WIN)/src/wcStreaming.o $(OBJDIR_RELEASE_WIN)/src/wcThread.o $(OBJDIR_RELEASE_WIN)/src/wcUtils.o $(OBJDIR_RELEASE_WIN)/wcwebcamclient.o $(OBJDIR_RELEASE_WIN)/cJSON/src/cJSON.o $(OBJDIR_RELEASE_WIN)/cJSON/src/cJSON_Utils.o

OBJ_DEBUG_LINUX = $(OBJDIR_DEBUG_LINUX)/src/wcHTTP2AsyncBackground.o $(OBJDIR_DEBUG_LINUX)/src/NotifyObj.o $(OBJDIR_DEBUG_LINUX)/src/tsCURLM.o $(OBJDIR_DEBUG_LINUX)/src/tsInteger.o $(OBJDIR_DEBUG_LINUX)/src/tsObject.o $(OBJDIR_DEBUG_LINUX)/src/tsSeq.o $(OBJDIR_DEBUG_LINUX)/src/tsStringList.o $(OBJDIR_DEBUG_LINUX)/src/wcCURLClient.o $(OBJDIR_DEBUG_LINUX)/src/wcCallbacks.o $(OBJDIR_DEBUG_LINUX)/src/wcConsts.o $(OBJDIR_DEBUG_LINUX)/src/wcHTTP2BackgroundTask.o $(OBJDIR_DEBUG_LINUX)/src/wcHTTP2SettingsIntf.o $(OBJDIR_DEBUG_LINUX)/src/wcJSON.o $(OBJDIR_DEBUG_LINUX)/src/wcMemoryStream.o $(OBJDIR_DEBUG_LINUX)/src/wcStreaming.o $(OBJDIR_DEBUG_LINUX)/src/wcThread.o $(OBJDIR_DEBUG_LINUX)/src/wcUtils.o $(OBJDIR_DEBUG_LINUX)/wcwebcamclient.o $(OBJDIR_DEBUG_LINUX)/cJSON/src/cJSON.o $(OBJDIR_DEBUG_LINUX)/cJSON/src/cJSON_Utils.o

OBJ_RELEASE_LINUX = $(OBJDIR_RELEASE_LINUX)/src/wcHTTP2AsyncBackground.o $(OBJDIR_RELEASE_LINUX)/src/NotifyObj.o $(OBJDIR_RELEASE_LINUX)/src/tsCURLM.o $(OBJDIR_RELEASE_LINUX)/src/tsInteger.o $(OBJDIR_RELEASE_LINUX)/src/tsObject.o $(OBJDIR_RELEASE_LINUX)/src/tsSeq.o $(OBJDIR_RELEASE_LINUX)/src/tsStringList.o $(OBJDIR_RELEASE_LINUX)/src/wcCURLClient.o $(OBJDIR_RELEASE_LINUX)/src/wcCallbacks.o $(OBJDIR_RELEASE_LINUX)/src/wcConsts.o $(OBJDIR_RELEASE_LINUX)/src/wcHTTP2BackgroundTask.o $(OBJDIR_RELEASE_LINUX)/src/wcHTTP2SettingsIntf.o $(OBJDIR_RELEASE_LINUX)/src/wcJSON.o $(OBJDIR_RELEASE_LINUX)/src/wcMemoryStream.o $(OBJDIR_RELEASE_LINUX)/src/wcStreaming.o $(OBJDIR_RELEASE_LINUX)/src/wcThread.o $(OBJDIR_RELEASE_LINUX)/src/wcUtils.o $(OBJDIR_RELEASE_LINUX)/wcwebcamclient.o $(OBJDIR_RELEASE_LINUX)/cJSON/src/cJSON.o $(OBJDIR_RELEASE_LINUX)/cJSON/src/cJSON_Utils.o

all: debug_win release_win debug_linux release_linux

clean: clean_debug_win clean_release_win clean_debug_linux clean_release_linux

before_debug_win: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG_WIN)/src || mkdir -p $(OBJDIR_DEBUG_WIN)/src
	test -d $(OBJDIR_DEBUG_WIN) || mkdir -p $(OBJDIR_DEBUG_WIN)
	test -d $(OBJDIR_DEBUG_WIN)/cJSON/src || mkdir -p $(OBJDIR_DEBUG_WIN)/cJSON/src

after_debug_win: 

debug_win: before_debug_win out_debug_win after_debug_win

out_debug_win: before_debug_win $(OBJ_DEBUG_WIN) $(DEP_DEBUG_WIN)
	$(LD) -shared $(LIBDIR_DEBUG_WIN) $(OBJ_DEBUG_WIN)  -o $(OUT_DEBUG_WIN) $(LDFLAGS_DEBUG_WIN) $(LIB_DEBUG_WIN)

$(OBJDIR_DEBUG_WIN)/src/wcHTTP2AsyncBackground.o: src/wcHTTP2AsyncBackground.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcHTTP2AsyncBackground.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcHTTP2AsyncBackground.o

$(OBJDIR_DEBUG_WIN)/src/NotifyObj.o: src/NotifyObj.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/NotifyObj.cpp -o $(OBJDIR_DEBUG_WIN)/src/NotifyObj.o

$(OBJDIR_DEBUG_WIN)/src/tsCURLM.o: src/tsCURLM.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/tsCURLM.cpp -o $(OBJDIR_DEBUG_WIN)/src/tsCURLM.o

$(OBJDIR_DEBUG_WIN)/src/tsInteger.o: src/tsInteger.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/tsInteger.cpp -o $(OBJDIR_DEBUG_WIN)/src/tsInteger.o

$(OBJDIR_DEBUG_WIN)/src/tsObject.o: src/tsObject.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/tsObject.cpp -o $(OBJDIR_DEBUG_WIN)/src/tsObject.o

$(OBJDIR_DEBUG_WIN)/src/tsSeq.o: src/tsSeq.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/tsSeq.cpp -o $(OBJDIR_DEBUG_WIN)/src/tsSeq.o

$(OBJDIR_DEBUG_WIN)/src/tsStringList.o: src/tsStringList.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/tsStringList.cpp -o $(OBJDIR_DEBUG_WIN)/src/tsStringList.o

$(OBJDIR_DEBUG_WIN)/src/wcCURLClient.o: src/wcCURLClient.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcCURLClient.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcCURLClient.o

$(OBJDIR_DEBUG_WIN)/src/wcCallbacks.o: src/wcCallbacks.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcCallbacks.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcCallbacks.o

$(OBJDIR_DEBUG_WIN)/src/wcConsts.o: src/wcConsts.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcConsts.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcConsts.o

$(OBJDIR_DEBUG_WIN)/src/wcHTTP2BackgroundTask.o: src/wcHTTP2BackgroundTask.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcHTTP2BackgroundTask.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcHTTP2BackgroundTask.o

$(OBJDIR_DEBUG_WIN)/src/wcHTTP2SettingsIntf.o: src/wcHTTP2SettingsIntf.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcHTTP2SettingsIntf.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcHTTP2SettingsIntf.o

$(OBJDIR_DEBUG_WIN)/src/wcJSON.o: src/wcJSON.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcJSON.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcJSON.o

$(OBJDIR_DEBUG_WIN)/src/wcMemoryStream.o: src/wcMemoryStream.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcMemoryStream.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcMemoryStream.o

$(OBJDIR_DEBUG_WIN)/src/wcStreaming.o: src/wcStreaming.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcStreaming.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcStreaming.o

$(OBJDIR_DEBUG_WIN)/src/wcThread.o: src/wcThread.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcThread.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcThread.o

$(OBJDIR_DEBUG_WIN)/src/wcUtils.o: src/wcUtils.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c src/wcUtils.cpp -o $(OBJDIR_DEBUG_WIN)/src/wcUtils.o

$(OBJDIR_DEBUG_WIN)/wcwebcamclient.o: wcwebcamclient.cpp
	$(CXX) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c wcwebcamclient.cpp -o $(OBJDIR_DEBUG_WIN)/wcwebcamclient.o

$(OBJDIR_DEBUG_WIN)/cJSON/src/cJSON.o: cJSON/src/cJSON.c
	$(CC) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c cJSON/src/cJSON.c -o $(OBJDIR_DEBUG_WIN)/cJSON/src/cJSON.o

$(OBJDIR_DEBUG_WIN)/cJSON/src/cJSON_Utils.o: cJSON/src/cJSON_Utils.c
	$(CC) $(CFLAGS_DEBUG_WIN) $(INC_DEBUG_WIN) -c cJSON/src/cJSON_Utils.c -o $(OBJDIR_DEBUG_WIN)/cJSON/src/cJSON_Utils.o

clean_debug_win: 
	rm -f $(OBJ_DEBUG_WIN) $(OUT_DEBUG_WIN)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG_WIN)/src
	rm -rf $(OBJDIR_DEBUG_WIN)
	rm -rf $(OBJDIR_DEBUG_WIN)/cJSON/src

before_release_win: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE_WIN)/src || mkdir -p $(OBJDIR_RELEASE_WIN)/src
	test -d $(OBJDIR_RELEASE_WIN) || mkdir -p $(OBJDIR_RELEASE_WIN)
	test -d $(OBJDIR_RELEASE_WIN)/cJSON/src || mkdir -p $(OBJDIR_RELEASE_WIN)/cJSON/src

after_release_win: 

release_win: before_release_win out_release_win after_release_win

out_release_win: before_release_win $(OBJ_RELEASE_WIN) $(DEP_RELEASE_WIN)
	$(LD) -shared $(LIBDIR_RELEASE_WIN) $(OBJ_RELEASE_WIN)  -o $(OUT_RELEASE_WIN) $(LDFLAGS_RELEASE_WIN) $(LIB_RELEASE_WIN)

$(OBJDIR_RELEASE_WIN)/src/wcHTTP2AsyncBackground.o: src/wcHTTP2AsyncBackground.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcHTTP2AsyncBackground.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcHTTP2AsyncBackground.o

$(OBJDIR_RELEASE_WIN)/src/NotifyObj.o: src/NotifyObj.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/NotifyObj.cpp -o $(OBJDIR_RELEASE_WIN)/src/NotifyObj.o

$(OBJDIR_RELEASE_WIN)/src/tsCURLM.o: src/tsCURLM.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/tsCURLM.cpp -o $(OBJDIR_RELEASE_WIN)/src/tsCURLM.o

$(OBJDIR_RELEASE_WIN)/src/tsInteger.o: src/tsInteger.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/tsInteger.cpp -o $(OBJDIR_RELEASE_WIN)/src/tsInteger.o

$(OBJDIR_RELEASE_WIN)/src/tsObject.o: src/tsObject.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/tsObject.cpp -o $(OBJDIR_RELEASE_WIN)/src/tsObject.o

$(OBJDIR_RELEASE_WIN)/src/tsSeq.o: src/tsSeq.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/tsSeq.cpp -o $(OBJDIR_RELEASE_WIN)/src/tsSeq.o

$(OBJDIR_RELEASE_WIN)/src/tsStringList.o: src/tsStringList.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/tsStringList.cpp -o $(OBJDIR_RELEASE_WIN)/src/tsStringList.o

$(OBJDIR_RELEASE_WIN)/src/wcCURLClient.o: src/wcCURLClient.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcCURLClient.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcCURLClient.o

$(OBJDIR_RELEASE_WIN)/src/wcCallbacks.o: src/wcCallbacks.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcCallbacks.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcCallbacks.o

$(OBJDIR_RELEASE_WIN)/src/wcConsts.o: src/wcConsts.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcConsts.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcConsts.o

$(OBJDIR_RELEASE_WIN)/src/wcHTTP2BackgroundTask.o: src/wcHTTP2BackgroundTask.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcHTTP2BackgroundTask.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcHTTP2BackgroundTask.o

$(OBJDIR_RELEASE_WIN)/src/wcHTTP2SettingsIntf.o: src/wcHTTP2SettingsIntf.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcHTTP2SettingsIntf.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcHTTP2SettingsIntf.o

$(OBJDIR_RELEASE_WIN)/src/wcJSON.o: src/wcJSON.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcJSON.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcJSON.o

$(OBJDIR_RELEASE_WIN)/src/wcMemoryStream.o: src/wcMemoryStream.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcMemoryStream.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcMemoryStream.o

$(OBJDIR_RELEASE_WIN)/src/wcStreaming.o: src/wcStreaming.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcStreaming.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcStreaming.o

$(OBJDIR_RELEASE_WIN)/src/wcThread.o: src/wcThread.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcThread.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcThread.o

$(OBJDIR_RELEASE_WIN)/src/wcUtils.o: src/wcUtils.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c src/wcUtils.cpp -o $(OBJDIR_RELEASE_WIN)/src/wcUtils.o

$(OBJDIR_RELEASE_WIN)/wcwebcamclient.o: wcwebcamclient.cpp
	$(CXX) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c wcwebcamclient.cpp -o $(OBJDIR_RELEASE_WIN)/wcwebcamclient.o

$(OBJDIR_RELEASE_WIN)/cJSON/src/cJSON.o: cJSON/src/cJSON.c
	$(CC) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c cJSON/src/cJSON.c -o $(OBJDIR_RELEASE_WIN)/cJSON/src/cJSON.o

$(OBJDIR_RELEASE_WIN)/cJSON/src/cJSON_Utils.o: cJSON/src/cJSON_Utils.c
	$(CC) $(CFLAGS_RELEASE_WIN) $(INC_RELEASE_WIN) -c cJSON/src/cJSON_Utils.c -o $(OBJDIR_RELEASE_WIN)/cJSON/src/cJSON_Utils.o

clean_release_win: 
	rm -f $(OBJ_RELEASE_WIN) $(OUT_RELEASE_WIN)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE_WIN)/src
	rm -rf $(OBJDIR_RELEASE_WIN)
	rm -rf $(OBJDIR_RELEASE_WIN)/cJSON/src

before_debug_linux: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG_LINUX)/src || mkdir -p $(OBJDIR_DEBUG_LINUX)/src
	test -d $(OBJDIR_DEBUG_LINUX) || mkdir -p $(OBJDIR_DEBUG_LINUX)
	test -d $(OBJDIR_DEBUG_LINUX)/cJSON/src || mkdir -p $(OBJDIR_DEBUG_LINUX)/cJSON/src

after_debug_linux: 

debug_linux: before_debug_linux out_debug_linux after_debug_linux

out_debug_linux: before_debug_linux $(OBJ_DEBUG_LINUX) $(DEP_DEBUG_LINUX)
	$(LD) -shared $(LIBDIR_DEBUG_LINUX) $(OBJ_DEBUG_LINUX)  -o $(OUT_DEBUG_LINUX) $(LDFLAGS_DEBUG_LINUX) $(LIB_DEBUG_LINUX)

$(OBJDIR_DEBUG_LINUX)/src/wcHTTP2AsyncBackground.o: src/wcHTTP2AsyncBackground.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcHTTP2AsyncBackground.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcHTTP2AsyncBackground.o

$(OBJDIR_DEBUG_LINUX)/src/NotifyObj.o: src/NotifyObj.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/NotifyObj.cpp -o $(OBJDIR_DEBUG_LINUX)/src/NotifyObj.o

$(OBJDIR_DEBUG_LINUX)/src/tsCURLM.o: src/tsCURLM.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/tsCURLM.cpp -o $(OBJDIR_DEBUG_LINUX)/src/tsCURLM.o

$(OBJDIR_DEBUG_LINUX)/src/tsInteger.o: src/tsInteger.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/tsInteger.cpp -o $(OBJDIR_DEBUG_LINUX)/src/tsInteger.o

$(OBJDIR_DEBUG_LINUX)/src/tsObject.o: src/tsObject.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/tsObject.cpp -o $(OBJDIR_DEBUG_LINUX)/src/tsObject.o

$(OBJDIR_DEBUG_LINUX)/src/tsSeq.o: src/tsSeq.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/tsSeq.cpp -o $(OBJDIR_DEBUG_LINUX)/src/tsSeq.o

$(OBJDIR_DEBUG_LINUX)/src/tsStringList.o: src/tsStringList.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/tsStringList.cpp -o $(OBJDIR_DEBUG_LINUX)/src/tsStringList.o

$(OBJDIR_DEBUG_LINUX)/src/wcCURLClient.o: src/wcCURLClient.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcCURLClient.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcCURLClient.o

$(OBJDIR_DEBUG_LINUX)/src/wcCallbacks.o: src/wcCallbacks.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcCallbacks.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcCallbacks.o

$(OBJDIR_DEBUG_LINUX)/src/wcConsts.o: src/wcConsts.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcConsts.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcConsts.o

$(OBJDIR_DEBUG_LINUX)/src/wcHTTP2BackgroundTask.o: src/wcHTTP2BackgroundTask.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcHTTP2BackgroundTask.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcHTTP2BackgroundTask.o

$(OBJDIR_DEBUG_LINUX)/src/wcHTTP2SettingsIntf.o: src/wcHTTP2SettingsIntf.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcHTTP2SettingsIntf.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcHTTP2SettingsIntf.o

$(OBJDIR_DEBUG_LINUX)/src/wcJSON.o: src/wcJSON.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcJSON.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcJSON.o

$(OBJDIR_DEBUG_LINUX)/src/wcMemoryStream.o: src/wcMemoryStream.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcMemoryStream.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcMemoryStream.o

$(OBJDIR_DEBUG_LINUX)/src/wcStreaming.o: src/wcStreaming.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcStreaming.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcStreaming.o

$(OBJDIR_DEBUG_LINUX)/src/wcThread.o: src/wcThread.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcThread.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcThread.o

$(OBJDIR_DEBUG_LINUX)/src/wcUtils.o: src/wcUtils.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c src/wcUtils.cpp -o $(OBJDIR_DEBUG_LINUX)/src/wcUtils.o

$(OBJDIR_DEBUG_LINUX)/wcwebcamclient.o: wcwebcamclient.cpp
	$(CXX) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c wcwebcamclient.cpp -o $(OBJDIR_DEBUG_LINUX)/wcwebcamclient.o

$(OBJDIR_DEBUG_LINUX)/cJSON/src/cJSON.o: cJSON/src/cJSON.c
	$(CC) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c cJSON/src/cJSON.c -o $(OBJDIR_DEBUG_LINUX)/cJSON/src/cJSON.o

$(OBJDIR_DEBUG_LINUX)/cJSON/src/cJSON_Utils.o: cJSON/src/cJSON_Utils.c
	$(CC) $(CFLAGS_DEBUG_LINUX) $(INC_DEBUG_LINUX) -c cJSON/src/cJSON_Utils.c -o $(OBJDIR_DEBUG_LINUX)/cJSON/src/cJSON_Utils.o

clean_debug_linux: 
	rm -f $(OBJ_DEBUG_LINUX) $(OUT_DEBUG_LINUX)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG_LINUX)/src
	rm -rf $(OBJDIR_DEBUG_LINUX)
	rm -rf $(OBJDIR_DEBUG_LINUX)/cJSON/src

before_release_linux: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE_LINUX)/src || mkdir -p $(OBJDIR_RELEASE_LINUX)/src
	test -d $(OBJDIR_RELEASE_LINUX) || mkdir -p $(OBJDIR_RELEASE_LINUX)
	test -d $(OBJDIR_RELEASE_LINUX)/cJSON/src || mkdir -p $(OBJDIR_RELEASE_LINUX)/cJSON/src

after_release_linux: 

release_linux: before_release_linux out_release_linux after_release_linux

out_release_linux: before_release_linux $(OBJ_RELEASE_LINUX) $(DEP_RELEASE_LINUX)
	$(LD) -shared $(LIBDIR_RELEASE_LINUX) $(OBJ_RELEASE_LINUX)  -o $(OUT_RELEASE_LINUX) $(LDFLAGS_RELEASE_LINUX) $(LIB_RELEASE_LINUX)

$(OBJDIR_RELEASE_LINUX)/src/wcHTTP2AsyncBackground.o: src/wcHTTP2AsyncBackground.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcHTTP2AsyncBackground.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcHTTP2AsyncBackground.o

$(OBJDIR_RELEASE_LINUX)/src/NotifyObj.o: src/NotifyObj.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/NotifyObj.cpp -o $(OBJDIR_RELEASE_LINUX)/src/NotifyObj.o

$(OBJDIR_RELEASE_LINUX)/src/tsCURLM.o: src/tsCURLM.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/tsCURLM.cpp -o $(OBJDIR_RELEASE_LINUX)/src/tsCURLM.o

$(OBJDIR_RELEASE_LINUX)/src/tsInteger.o: src/tsInteger.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/tsInteger.cpp -o $(OBJDIR_RELEASE_LINUX)/src/tsInteger.o

$(OBJDIR_RELEASE_LINUX)/src/tsObject.o: src/tsObject.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/tsObject.cpp -o $(OBJDIR_RELEASE_LINUX)/src/tsObject.o

$(OBJDIR_RELEASE_LINUX)/src/tsSeq.o: src/tsSeq.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/tsSeq.cpp -o $(OBJDIR_RELEASE_LINUX)/src/tsSeq.o

$(OBJDIR_RELEASE_LINUX)/src/tsStringList.o: src/tsStringList.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/tsStringList.cpp -o $(OBJDIR_RELEASE_LINUX)/src/tsStringList.o

$(OBJDIR_RELEASE_LINUX)/src/wcCURLClient.o: src/wcCURLClient.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcCURLClient.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcCURLClient.o

$(OBJDIR_RELEASE_LINUX)/src/wcCallbacks.o: src/wcCallbacks.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcCallbacks.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcCallbacks.o

$(OBJDIR_RELEASE_LINUX)/src/wcConsts.o: src/wcConsts.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcConsts.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcConsts.o

$(OBJDIR_RELEASE_LINUX)/src/wcHTTP2BackgroundTask.o: src/wcHTTP2BackgroundTask.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcHTTP2BackgroundTask.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcHTTP2BackgroundTask.o

$(OBJDIR_RELEASE_LINUX)/src/wcHTTP2SettingsIntf.o: src/wcHTTP2SettingsIntf.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcHTTP2SettingsIntf.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcHTTP2SettingsIntf.o

$(OBJDIR_RELEASE_LINUX)/src/wcJSON.o: src/wcJSON.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcJSON.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcJSON.o

$(OBJDIR_RELEASE_LINUX)/src/wcMemoryStream.o: src/wcMemoryStream.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcMemoryStream.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcMemoryStream.o

$(OBJDIR_RELEASE_LINUX)/src/wcStreaming.o: src/wcStreaming.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcStreaming.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcStreaming.o

$(OBJDIR_RELEASE_LINUX)/src/wcThread.o: src/wcThread.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcThread.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcThread.o

$(OBJDIR_RELEASE_LINUX)/src/wcUtils.o: src/wcUtils.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c src/wcUtils.cpp -o $(OBJDIR_RELEASE_LINUX)/src/wcUtils.o

$(OBJDIR_RELEASE_LINUX)/wcwebcamclient.o: wcwebcamclient.cpp
	$(CXX) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c wcwebcamclient.cpp -o $(OBJDIR_RELEASE_LINUX)/wcwebcamclient.o

$(OBJDIR_RELEASE_LINUX)/cJSON/src/cJSON.o: cJSON/src/cJSON.c
	$(CC) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c cJSON/src/cJSON.c -o $(OBJDIR_RELEASE_LINUX)/cJSON/src/cJSON.o

$(OBJDIR_RELEASE_LINUX)/cJSON/src/cJSON_Utils.o: cJSON/src/cJSON_Utils.c
	$(CC) $(CFLAGS_RELEASE_LINUX) $(INC_RELEASE_LINUX) -c cJSON/src/cJSON_Utils.c -o $(OBJDIR_RELEASE_LINUX)/cJSON/src/cJSON_Utils.o

clean_release_linux: 
	rm -f $(OBJ_RELEASE_LINUX) $(OUT_RELEASE_LINUX)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE_LINUX)/src
	rm -rf $(OBJDIR_RELEASE_LINUX)
	rm -rf $(OBJDIR_RELEASE_LINUX)/cJSON/src

.PHONY: before_debug_win after_debug_win clean_debug_win before_release_win after_release_win clean_release_win before_debug_linux after_debug_linux clean_debug_linux before_release_linux after_release_linux clean_release_linux

